### ISSUE TITLE
Wallet 2.0.1 keeps restarting coin daemon

### ISSUE THREAD

**Issue by mtl1979** [oliviersinnaeve/b2bcoin-wallet#12]
When wallet starts, it waits for coin daemon to start synchronizing the blockchain, but after few seconds, coin daemon dies without error message and is restarted.

**Comment by oliviersinnaeve** [comment]
This is a fix we introduced just for the daemon dying on us. This mechanisme restarts the daemon as long as needed until synchronizing is back to going on.
