### ISSUE TITLE
Fusion transaction succeeds but wallet gives error message...

### ISSUE THREAD

**Issue by mtl1979** [oliviersinnaeve/b2bcoin-wallet#21]
If user tries fusion transaction right after starting wallet, wallet gives error message "Fusion failed : null" but fusion transaction is still sent to blockchain and appears in transaction logs. 
Root cause of the error message might be timeout caused by high CPU load.

**Comment by oliviersinnaeve** [comment]
Augmented timeout to 5 minutes for fusion command - version 2.0.2
