### ISSUE TITLE
No private view key in GUI Mac wallet.

### ISSUE THREAD

**Issue by ghost** [oliviersinnaeve/b2bcoin-wallet#7]
So here is what I did
I created a wallet in CLI
did export_keys
and then imported the wallet in GUI. 
when I see "spend keys" in GUI - secret spend key is same
but spend public key is different from secret view key given by "export_key"

**Comment by oliviersinnaeve** [comment]
Do you get the same address ? We are still investigating the key story ...

**Comment by ghost** [comment]
If I import CLI wallet into GUI - i get correct address.

If I import GUI wallet into CLI - I get wrong one, as the keys are not available.

**Comment by oliviersinnaeve** [comment]
Showing all 3 keys in version 2.0.2
