### ISSUE TITLE
password confirmation

### ISSUE THREAD

**Issue by ntm78** [oliviersinnaeve/b2bcoin-wallet#8]
Hi
When we create a new wallet, can you create a password confirmation system, so user cant create a wallet with an error in his password.
So wallet won t be lost.
thanks a lot

regards ;)

**Comment by pharmecis** [comment]
Doulbe password entry was asked for in Telegram several times.  Dev even requested for this issue to be posted to github back on the 8th of February and never did anything about it.  I have now evidently fat fingered a password and have lost enough coin to be upset for a dev not implementing a simple function that could save many people a large headache.

#@$@# Coin...

**Comment by oliviersinnaeve** [comment]
Fixed in version 2.0.2 - Dedicated to Greg Morron
