### ISSUE TITLE
Adjust size

### ISSUE THREAD

**Issue by Fungraphic** [oliviersinnaeve/b2bcoin-wallet#9]
We can not adjust the size.
Can you change that?
Thank you

**Comment by oliviersinnaeve** [comment]
Size of what ??

**Comment by Fungraphic** [comment]
Can you add the possiblity fo us to asjust the size of the wallet, especially to make it smaller

**Comment by djriffle** [comment]
The minimum height and width of the wallet can be edited in configs/application.config

**Comment by oliviersinnaeve** [comment]
@djriffle  This was broken in version 2.0.0
Will be back in version 2.0.2
